import { ClientFormValues } from "../schema/client-zod-schema";

//steps we created in the stepper
export const steps = [
  {
    id: "Step 1",
    name: "Client General Information",
    fields: [
      "firstName",
      "middleName",
      "lastName",
      "suffix",
      "dateOfBirth",
      "gender",
      "addressLine1",
      "addressLine2",
      "barangay",
      "cityOrMunicipality",
      "province",
      "region",
      "zipCode",
      "primaryContact",
      "secondaryContact",
      "religion",
      "civilStatus",
      "occupation",
      "mothersMaidenName",
      "placeOfBirth",
    ],
  },
  {
    id: "Step 2",
    name: "Client's Family Information",
    fields: [
      "spouseFirstName",
      "spouseMiddleName",
      "spouseLastName",
      "spouseDateOfBirth",
      "spouseContactNumber",
      "spouseAddressLine1",
      "spouseAddressLine2",
      "spouseBarangay",
      "spouseCityOrMunicipality",
      "spouseProvince",
      "spouseRegion",
      "spouseZipCode",

      "firstChildName",
      "firstChildDateOfBirth",
      "firstChildAddressLine1",
      "firstChildAddressLine2",
      "firstChildBarangay",
      "firstChildCityOrMunicipality",
      "firstChildProvince",
      "firstChildRegion",
      "firstChildZipCode",

      "secondChildName",
      "secondChildDateOfBirth",
      "secondChildAddressLine1",
      "secondChildAddressLine2",
      "secondChildBarangay",
      "secondChildCityOrMunicipality",
      "secondChildProvince",
      "secondChildRegion",
      "secondChildZipCode",

      "thirdChildName",
      "thirdChildDateOfBirth",
      "thirdChildAddressLine1",
      "thirdChildAddressLine2",
      "thirdChildBarangay",
      "thirdChildCityOrMunicipality",
      "thirdChildProvince",
      "thirdChildRegion",
      "thirdChildZipCode",
    ],
  },
  {
    id: "Step 3",
    name: "Pensioner's Information",
    fields: [
      "rank",
      "pensionType",
      "serialNumber",
      "idNumber",
      "dateEnteredService",
      "dateSeparationService",
      "dateRetiredService",
      "lengthOfService",
      "lastUnitAssigned",
      "branchOfService",
    ],
  },
  {
    id: "Step 4",
    name: "Account's Information",
    fields: ["monthlyPension", "monthlyDeduction", "atmAccountNumber", "bankName", "branchOfBank"],
  },
];

// Default Values in Forms
export const defaultValues = {
  firstName: "",
  middleName: "",
  lastName: "",
  suffix: "",
  dateOfBirth: new Date(),
  gender: "",
  addressLine1: "",
  addressLine2: "",
  barangay: "",
  cityOrMunicipality: "",
  province: "",
  region: "",
  zipCode: 0,
  primaryContact: "",
  secondaryContact: "",
  religion: "",
  civilStatus: "",
  occupation: "",
  mothersMaidenName: "",
  placeOfBirth: "",

  spouseFirstName: "",
  spouseMiddleName: "",
  spouseLastName: "",
  spouseDateOfBirth: new Date(),
  spouseContactNumber: undefined,
  spouseAddressSameAsClient: false,
  spouseAddressLine1: "",
  spouseAddressLine2: "",
  spouseBarangay: "",
  spouseCityOrMunicipality: "",
  spouseProvince: "",
  spouseRegion: "",
  spouseZipCode: 0,

  firstChildName: "",
  firstChildDateOfBirth: new Date(),
  firstChildAddressSameAsClient: false,
  firstChildAddressSameAsSpouse: false,
  firstChildAddressLine1: "",
  firstChildAddressLine2: "",
  firstChildBarangay: "",
  firstChildCityOrMunicipality: "",
  firstChildProvince: "",
  firstChildRegion: "",
  firstChildZipCode: 0,

  secondChildName: "",
  secondChildDateOfBirth: new Date(),
  secondChildAddressSameAsClient: false,
  secondChildAddressSameAsSpouse: false,
  secondChildAddressLine1: "",
  secondChildAddressLine2: "",
  secondChildBarangay: "",
  secondChildCityOrMunicipality: "",
  secondChildProvince: "",
  secondChildRegion: "",
  secondChildZipCode: 0,

  thirdChildName: "",
  thirdChildDateOfBirth: new Date(),
  thirdChildAddressSameAsClient: false,
  thirdChildAddressSameAsSpouse: false,
  thirdChildAddressLine1: "",
  thirdChildAddressLine2: "",
  thirdChildBarangay: "",
  thirdChildCityOrMunicipality: "",
  thirdChildProvince: "",
  thirdChildRegion: "",
  thirdChildZipCode: 0,
  rank: "",
  pensionType: "",
  serialNumber: "",
  idNumber: "",
  dateEnteredService: new Date(),
  dateSeparationService: new Date(),
  dateRetiredService: new Date(),
  lengthOfService: 0,
  lastUnitAssigned: "",
  branchOfService: "",
  monthlyPension: 0,
  monthlyDeduction: 0,
  atmAccountNumber: "",
  bankName: "",
  branchOfBank: "",
};

// The 'keyof ClientFormValues' type ensures that each value in the 'formDates' array
// matches a valid key from the 'ClientFormValues' type. This prevents typos or invalid keys
// by allowing only existing property names of 'ClientFormValues'.
export const formDates: (keyof ClientFormValues)[] = [
  "dateOfBirth",
  "spouseDateOfBirth",
  "firstChildDateOfBirth",
  "secondChildDateOfBirth",
  "thirdChildDateOfBirth",
  "dateEnteredService",
  "dateSeparationService",
  "dateRetiredService",
];

// This will be used to make the dates null if the dates of this component are untouched
export const optionalFormDates: (keyof ClientFormValues)[] = [
  "spouseDateOfBirth",
  "firstChildDateOfBirth",
  "secondChildDateOfBirth",
  "thirdChildDateOfBirth",
];
